name: Space Invaders Disassembler and Emulator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Disassembler Executable
        run: ${{ github.workspace }}/build.sh
